### PR TITLE
Correcting default behavior on restore.

### PR DESCRIPTION
**Pull request by Qrzy**
In current implementation, even though "Y" option is being suggested to be default on restore question, when no input is given, restore is being skipped like there was "n" given.

### CODE REVIEW

**Comment by IzzySoft** [comment]
Thanks! But with your changes, restore would also take place if one accidentally hits "m" or "b" (i.e. misses the "n" key closely), which I feel much more dangerous. A better solution might be to check for "y" (as it is done now) and in addition for "empty", i.e. `echo "  if [[ \"\${res,,}\" = \"y\" || -z \"\${res}\" ]]; then"`, wouldn't you agree?

**Comment by Qrzy** [comment]
You are absolutely right, just corrected it. 

By the way - awesome idea and very nice tool, congrats. :)

**Comment by IzzySoft** [comment]
Looks cool now :) Maybe doing the same for the y/n on shared storage (further down within the same function)? Then I'd merge it all together.

And thanks for the compliments – always good to see something created out of a necessity proves help- and useful to others :)

**Comment by Qrzy** [comment]
I didn't see that before, thanks for pointer. :+1:

**Comment by IzzySoft** [comment]
Thanks a lot – just merged it! :+1:

**Pull request merged**
