### PR TITLE
Some fixes and extra options

### PR DESCRIPTION
**Pull request by Flashwalker**
### For doc:

**Fixed**: packagedata.lib: aapt output parsing

*In my case i had this string instead of apps names*: `/system/bin/sh: sed: not found`

**Fixed**: deviceinfo.lib: check whether `uname` in $PATH or use `busybox uname`

*In my case Kernel was empty*: `* Kernel: `

### For backup:

**Added**: adebar-cli, config.sample, scriptgen.lib: options for userbackup and sysbackup scripts, so if the script was hanged (adb chokes) and you terminated with <kbd>Ctrl + C</kbd> and restarted again it starts backup at aborted point (means keep already existing backup files: no need to edit script)

*In my case backup script hangs often enough in autoconfirm mode - when confirm prompt сeases to appear due adb choked*

**Added**: adebar-cli, config.sample, scriptgen.lib: option for backup shared storage without prompt

**Added**: scriptgen.lib: interactive retry to backup 41-byte apps

*In my case some of the apps was backed up as 41-byte at first, but retrying was succesfull for few*

*But still 41-byte user apps are these 20*:

* com.github.dfa.diaspora_android - dandelion\*
* org.gc.networktester - Network Tester
* org.mustard.android - Mustard
* info.guardianproject.lildebi - Lil Debi
* org.sufficientlysecure.keychain - OpenKeychain
* com.uc.browser.hd - UC Browser HD
* org.thialfihar.android.apg - APG
* org.mariotaku.imageviewergl - GLImageViewer
* eu.faircode.netguard - NetGuard
* org.xposeddownloader - Xposed Downloader
* info.guardianproject.browser - Orweb
* org.mozilla.firefox - Firefox
* com.opera.browser - Opera
* org.torproject.android - Orbot
* org.telegram.messenger - Telegram
* org.holidates.ekadasi - Ekadasi
* com.UCMobile.intl - UC Browser
* dev.ukanth.ufirewall - AFWall+
* info.guardianproject.gpg - GnuPrivacyGuard
* com.trueconf.videochat - TrueConf

*and 41-byte system apps are these 17*:

* com.android.vpndialogs - Android VPN Dialogs
* android.rk.RockVideoPlayer
* com.android.provision - Android Provision
* com.android.backupconfirm - Android BackupConfirm
* com.android.systemui - Android SystemUI
* com.android.providers.telephony - Android TelephonyProvider
* com.android.defcontainer - Android DefaultContainerService
* com.android.packageinstaller - Android Package Installer
* com.android.phone - Android Phone App
* com.android.sharedstoragebackup - Android Shared Storage Backup
* com.android.keychain - Android KeyChain
* com.android.launcher - Android Launcher
* com.android.inputdevices - Android InputDevices
* com.android.providers.drm - Android DRMProvider
* com.android.settings - Android Settings
* com.android.calculator2 - Calculator
* com.android.certinstaller - Android Certificate Installer

for fully rooted *IconBIT NetTAB Sky III*

### CODE REVIEW

**Comment by Flashwalker** [comment]
Looks like deviceinfo.lib and packagedata.lib contains different line endings and Sublime has broke something

**Comment by Flashwalker** [comment]
I'm confused. Is it normal this strange line break here?: https://github.com/IzzySoft/Adebar/blob/master/lib/deviceinfo.lib#L63
Just opened in Vim and found it's `^M`, but other editors opens and saves it as new line break, and git sees diff.
What editor do you use for saving it properly?

**Comment by IzzySoft** [comment]
Yes, and careful – breaking that breaks the app. We have to deal with the fact that ADB returns some things with Windows linebreaks. The line you just pointed to is one of those examples.

In short: where there are ^M (CR) in the code now, they must remain. Do not convert the charset for editing, take care you use an editor that keeps them intact.

**Comment by Flashwalker** [comment]
ok

**Pull request closed without merging**
