### PR TITLE
Added optional automated confirmation for backups

### PR DESCRIPTION
**Pull request by inktrap**
- I implemented optional automated confirmation for backups.
- Adebar's backup function wil be running in the background, so confirmation keycodes can be sent.
- I tested the script-generation and the resulting script and they both work.
- Also I tried to follow the Adebar coding-style, if you have any suggestions, tell me
- I think this ability is very important and adds greatly to the usability of Adebar

### CODE REVIEW

**Comment by inktrap** [comment]
Also I updated the config in my branch with a note that spaces are currently not supported in passwords, but this is not included in this PR. So feel free to add it.

Btw.: Making spaces work would require to split the password, then enter each segment, then the space via keyevent 62. (This won't work, see comment below)

**Comment by inktrap** [comment]
1) I tried implementing the fix for spaces in passwords and entering them works. But if there are more than two spaces, the keyboard will be visible and the following keycodes fail.

2) I also tried including spaces inline "like%sthis", which is much nicer than 1) but that gave the same results. Therefore I won't be implementing this. No spaces for backup-passwords, keycodes are to fragile.

**Comment by IzzySoft** [comment]
Thanks a lot! This sounds good – an on a quick investigation also looks good, so I will merge this PR. It requires an additional change, though: As using a config file is optional, defaults for the two new settings need to be placed in `adebar_cli` as well. Until approved by more devices/users, I'll put `AUTO_CONFIRM=0` there for now.

Speaking of which: May I ask you to add your device details to issue #7?

**Comment by IzzySoft** [comment]
PS: Any plans to support this with the restore scripts as well?

**Comment by inktrap** [comment]
re: restore scripts: sure, why not? Haven't looked at them yet
and have not tried restoring at all.

Excerpts from Izzy's message of 2015-11-08 15:18:08 +0100:

**Comment by IzzySoft** [comment]
Thanks in advance! No need to "hurry" – whenever you find time is fine. Before compiling this into a new "release", I just think it should be "complete" :)

**Pull request merged**
